

##
## All memrd instance constraints and waiver
##


set_false_path -from [get_pins -filter {REF_PIN_NAME=~CLK*} -of_objects [get_cells -hierarchical -filter {NAME =~ "*cc_axis_mu0/inst/MU_EQ.L2_*FULL*.u_eq/*cfglut*"}]] -to [get_pins -filter {REF_PIN_NAME=~D*} -of_objects [get_cells -hierarchical -filter {NAME =~ "*axis_cap_ctrl/inst/scnt_cmp_q*"}]]
set_false_path -from [get_pins -filter {REF_PIN_NAME=~CLK*} -of_objects [get_cells -hierarchical -filter {NAME =~ "*cc_axis_mu1/inst/MU_EQ.L2_*FULL*.u_eq/*cfglut*"}]] -to [get_pins -filter {REF_PIN_NAME=~D*} -of_objects [get_cells -hierarchical -filter {NAME =~ "*axis_cap_ctrl/inst/scnt_max_cmp_q*"}]]
set_false_path -from [get_pins -filter {REF_PIN_NAME=~CLK*} -of_objects [get_cells -hierarchical -filter {NAME =~ "*cc_axis_mu2/inst/MU_EQ.L2_*FULL*.u_eq/*cfglut*"}]] -to [get_pins -filter {REF_PIN_NAME=~D*} -of_objects [get_cells -hierarchical -filter {NAME =~ "*axis_cap_ctrl/inst/wcnt_hcmp_q*"}]]
set_false_path -from [get_pins -filter {REF_PIN_NAME=~CLK*} -of_objects [get_cells -hierarchical -filter {NAME =~ "*cc_axis_mu3/inst/MU_EQ.L2_*FULL*.u_eq/*cfglut*"}]] -to [get_pins -filter {REF_PIN_NAME=~D*} -of_objects [get_cells -hierarchical -filter {NAME =~ "*axis_cap_ctrl/inst/wcnt_lcmp_q*"}]]
create_waiver -type CDC -id CDC-1 -from [get_pins -filter {REF_PIN_NAME=~CLK*} -of_objects [get_cells *cc_axis_mu0/inst/MU_EQ.L2_*FULL*.u_eq/*cfglut*]] -to [get_pins -filter {REF_PIN_NAME=~D*} -of_objects [get_cells *axis_cap_ctrl/inst/scnt_cmp_q*]]     -user "axis_ila" -description {This CDC is coming in Match unit of ILA. After the source gets updated, there is very large time after which the destination get the value.} -tags "1052662" -scope -internal 
create_waiver -type CDC -id CDC-1 -from [get_pins -filter {REF_PIN_NAME=~CLK*} -of_objects [get_cells *cc_axis_mu1/inst/MU_EQ.L2_*FULL*.u_eq/*cfglut*]] -to [get_pins -filter {REF_PIN_NAME=~D*} -of_objects [get_cells *axis_cap_ctrl/inst/scnt_max_cmp_q*]] -user "axis_ila" -description {This CDC is coming in Match unit of ILA. After the source gets updated, there is very large time after which the destination get the value.} -tags "1052662" -scope -internal 
create_waiver -type CDC -id CDC-1 -from [get_pins -filter {REF_PIN_NAME=~CLK*} -of_objects [get_cells *cc_axis_mu2/inst/MU_EQ.L2_*FULL*.u_eq/*cfglut*]] -to [get_pins -filter {REF_PIN_NAME=~D*} -of_objects [get_cells *axis_cap_ctrl/inst/wcnt_hcmp_q*]]    -user "axis_ila" -description {This CDC is coming in Match unit of ILA. After the source gets updated, there is very large time after which the destination get the value.} -tags "1052662" -scope -internal 
create_waiver -type CDC -id CDC-1 -from [get_pins -filter {REF_PIN_NAME=~CLK*} -of_objects [get_cells *cc_axis_mu3/inst/MU_EQ.L2_*FULL*.u_eq/*cfglut*]] -to [get_pins -filter {REF_PIN_NAME=~D*} -of_objects [get_cells *axis_cap_ctrl/inst/wcnt_lcmp_q*]]    -user "axis_ila" -description {This CDC is coming in Match unit of ILA. After the source gets updated, there is very large time after which the destination get the value.} -tags "1052662" -scope -internal 

set_false_path -from [get_pins -filter {REF_PIN_NAME=~CLK*} -of_objects [get_cells -hierarchical -filter {NAME =~ "*cc_axis_mu0/inst/MU_EQ.drive_srl/S1*"}]] -to [get_pins -filter {REF_PIN_NAME=~D*} -of_objects [get_cells -hierarchical -filter {NAME =~ "*axis_cap_ctrl/inst/scnt_cmp_q*"}]]
set_false_path -from [get_pins -filter {REF_PIN_NAME=~CLK*} -of_objects [get_cells -hierarchical -filter {NAME =~ "*cc_axis_mu1/inst/MU_EQ.drive_srl/S1*"}]] -to [get_pins -filter {REF_PIN_NAME=~D*} -of_objects [get_cells -hierarchical -filter {NAME =~ "*axis_cap_ctrl/inst/scnt_max_cmp_q*"}]]
set_false_path -from [get_pins -filter {REF_PIN_NAME=~CLK*} -of_objects [get_cells -hierarchical -filter {NAME =~ "*cc_axis_mu2/inst/MU_EQ.drive_srl/S1*"}]] -to [get_pins -filter {REF_PIN_NAME=~D*} -of_objects [get_cells -hierarchical -filter {NAME =~ "*axis_cap_ctrl/inst/wcnt_hcmp_q*"}]]
set_false_path -from [get_pins -filter {REF_PIN_NAME=~CLK*} -of_objects [get_cells -hierarchical -filter {NAME =~ "*cc_axis_mu3/inst/MU_EQ.drive_srl/S1*"}]] -to [get_pins -filter {REF_PIN_NAME=~D*} -of_objects [get_cells -hierarchical -filter {NAME =~ "*axis_cap_ctrl/inst/wcnt_lcmp_q*"}]]
create_waiver -type CDC -id CDC-1 -from [get_pins -filter {REF_PIN_NAME=~CLK*} -of_objects [get_cells *cc_axis_mu0/inst/MU_EQ.drive_srl/S1*]] -to [get_pins -filter {REF_PIN_NAME=~D*} -of_objects [get_cells *axis_cap_ctrl/inst/scnt_cmp_q*]]     -user "axis_ila" -description {This CDC is coming in Match unit of ILA. After the source gets updated, there is very large time after which the destination get the value.} -tags "1052662" -scope -internal 
create_waiver -type CDC -id CDC-1 -from [get_pins -filter {REF_PIN_NAME=~CLK*} -of_objects [get_cells *cc_axis_mu1/inst/MU_EQ.drive_srl/S1*]] -to [get_pins -filter {REF_PIN_NAME=~D*} -of_objects [get_cells *axis_cap_ctrl/inst/scnt_max_cmp_q*]] -user "axis_ila" -description {This CDC is coming in Match unit of ILA. After the source gets updated, there is very large time after which the destination get the value.} -tags "1052662" -scope -internal 
create_waiver -type CDC -id CDC-1 -from [get_pins -filter {REF_PIN_NAME=~CLK*} -of_objects [get_cells *cc_axis_mu2/inst/MU_EQ.drive_srl/S1*]] -to [get_pins -filter {REF_PIN_NAME=~D*} -of_objects [get_cells *axis_cap_ctrl/inst/wcnt_hcmp_q*]]    -user "axis_ila" -description {This CDC is coming in Match unit of ILA. After the source gets updated, there is very large time after which the destination get the value.} -tags "1052662" -scope -internal 
create_waiver -type CDC -id CDC-1 -from [get_pins -filter {REF_PIN_NAME=~CLK*} -of_objects [get_cells *cc_axis_mu3/inst/MU_EQ.drive_srl/S1*]] -to [get_pins -filter {REF_PIN_NAME=~D*} -of_objects [get_cells *axis_cap_ctrl/inst/wcnt_lcmp_q*]]    -user "axis_ila" -description {This CDC is coming in Match unit of ILA. After the source gets updated, there is very large time after which the destination get the value.} -tags "1052662" -scope -internal 

set_false_path -from [get_pins -filter {REF_PIN_NAME=~CLK*} -of_objects [get_cells -hierarchical -filter {NAME =~ "*cc_axis_mu0/inst/MU_EQ.drive_srl/S2*"}]] -to [get_pins -filter {REF_PIN_NAME=~D*} -of_objects [get_cells -hierarchical -filter {NAME =~ "*axis_cap_ctrl/inst/scnt_cmp_q*"}]]
set_false_path -from [get_pins -filter {REF_PIN_NAME=~CLK*} -of_objects [get_cells -hierarchical -filter {NAME =~ "*cc_axis_mu1/inst/MU_EQ.drive_srl/S2*"}]] -to [get_pins -filter {REF_PIN_NAME=~D*} -of_objects [get_cells -hierarchical -filter {NAME =~ "*axis_cap_ctrl/inst/scnt_max_cmp_q*"}]]
set_false_path -from [get_pins -filter {REF_PIN_NAME=~CLK*} -of_objects [get_cells -hierarchical -filter {NAME =~ "*cc_axis_mu2/inst/MU_EQ.drive_srl/S2*"}]] -to [get_pins -filter {REF_PIN_NAME=~D*} -of_objects [get_cells -hierarchical -filter {NAME =~ "*axis_cap_ctrl/inst/wcnt_hcmp_q*"}]]
set_false_path -from [get_pins -filter {REF_PIN_NAME=~CLK*} -of_objects [get_cells -hierarchical -filter {NAME =~ "*cc_axis_mu3/inst/MU_EQ.drive_srl/S2*"}]] -to [get_pins -filter {REF_PIN_NAME=~D*} -of_objects [get_cells -hierarchical -filter {NAME =~ "*axis_cap_ctrl/inst/wcnt_lcmp_q*"}]]
create_waiver -type CDC -id CDC-1 -from [get_pins -filter {REF_PIN_NAME=~CLK*} -of_objects [get_cells *cc_axis_mu0/inst/MU_EQ.drive_srl/S2*]] -to [get_pins -filter {REF_PIN_NAME=~D*} -of_objects [get_cells *axis_cap_ctrl/inst/scnt_cmp_q*]]     -user "axis_ila" -description {This CDC is coming in Match unit of ILA. After the source gets updated, there is very large time after which the destination get the value.} -tags "1052662" -scope -internal 
create_waiver -type CDC -id CDC-1 -from [get_pins -filter {REF_PIN_NAME=~CLK*} -of_objects [get_cells *cc_axis_mu1/inst/MU_EQ.drive_srl/S2*]] -to [get_pins -filter {REF_PIN_NAME=~D*} -of_objects [get_cells *axis_cap_ctrl/inst/scnt_max_cmp_q*]] -user "axis_ila" -description {This CDC is coming in Match unit of ILA. After the source gets updated, there is very large time after which the destination get the value.} -tags "1052662" -scope -internal 
create_waiver -type CDC -id CDC-1 -from [get_pins -filter {REF_PIN_NAME=~CLK*} -of_objects [get_cells *cc_axis_mu2/inst/MU_EQ.drive_srl/S2*]] -to [get_pins -filter {REF_PIN_NAME=~D*} -of_objects [get_cells *axis_cap_ctrl/inst/wcnt_hcmp_q*]]    -user "axis_ila" -description {This CDC is coming in Match unit of ILA. After the source gets updated, there is very large time after which the destination get the value.} -tags "1052662" -scope -internal 
create_waiver -type CDC -id CDC-1 -from [get_pins -filter {REF_PIN_NAME=~CLK*} -of_objects [get_cells *cc_axis_mu3/inst/MU_EQ.drive_srl/S2*]] -to [get_pins -filter {REF_PIN_NAME=~D*} -of_objects [get_cells *axis_cap_ctrl/inst/wcnt_lcmp_q*]]    -user "axis_ila" -description {This CDC is coming in Match unit of ILA. After the source gets updated, there is very large time after which the destination get the value.} -tags "1052662" -scope -internal 

create_waiver -type CDC -id CDC-11 -to [get_pins *axis_dbg_sync_6/inst/genblk1.xpm_cdc_async_rst_inst/arststages_ff_reg[0]/CLR]  -user "axis_ila" -description {This CDC is coming in axis_dbg_sync_6 of ILA. After the source gets updated, there is very large time after which the destination get the value.} -tags "1052662" -scope -internal

